### ISSUE TITLE
Environment markers not respected by check-requirements

### ISSUE THREAD

**Issue by julianjk** [Yelp/requirements-tools#44]
When using environment markers in requirements.txt, I found that check-requirements did not respect the environment marker when checking requirements. Example:
requirements.txt containing something like:
`functools32==3.2.3.post2;python_version<"3.0"`
resulted in errors like: 
```
__ ERROR at setup of test_no_duplicate_requirements __
.tox/py36/lib/python3.6/site-packages/requirements_tools/check_requirements.py:164: in check_requirements_integrity
    req.key, filename,
E   AssertionError: functools32 is required in requirements.txt, but is not installed
```

despite running this in Python3. Looks like some logic may need to be added around https://github.com/Yelp/requirements-tools/blob/master/requirements_tools/check_requirements.py#L164-L187

**Comment by asottile** [comment]
the tools are intended for a single version of python (you'd both create the requirements.txt using that version and run with that version) -- for this case, you'd simply remove `functools32` since you're not targetting python3.x

**Comment by julianjk** [comment]
My goal here was to build with both py2 and py3, but in that case feel free to close this issue.

Also I think you may have meant python2.x, as I am targeting python3.x. 

Thanks for taking a look and the quick response!

**Comment by asottile** [comment]
indeeeeed -- yep that was a typo -- you may find [pip-tools](https://github.com/jazzband/pip-tools) more featureful / less opinionated in this regard 👍
