### ISSUE TITLE
allow --binary-only=:all: on upgrade-requirements 

### ISSUE THREAD

**Issue by lydian** [Yelp/requirements-tools#50]
It would be great if upgrade-requirements would only bump the package version when the binary build exist, otherwise we will always need to pin the version in the minimal file which would be a issue to maintain the minimal.txt file.

**Comment by asottile** [comment]
you can do this without changing any code:

```bash
PIP_BINARY_ONLY=:all: upgrade-requirements
```

**Comment by asottile** [comment]
also `--pip-tool 'pip --binary-only=:all:'`

**Comment by suntzu86** [comment]
Note, the title & commands have the option name backwards. Threw me off for a minute, lol.

You want
```
PIP_ONLY_BINARY=:all: upgrade-requirements ...
```
or
```
upgrade-requirements ... --pip-tool 'pip --only-binary=:all:'
```
although i personally find the second one more readable/compact.

and works fine (unsurprisingly) with `pip-custom-platform` too.

**Comment by asottile** [comment]
note that `--only-binary` can *sometimes* give you false positives if a wheel exists in your cache so be careful with it

**Comment by suntzu86** [comment]
@asottile so safest to suggest that developers delete their caches after we add this option?

**Comment by asottile** [comment]
I would never suggest deleting caches, that's a good way to waste a bunch of developer time.  your *best* bet is to temporarily redirect the cache directory via `XDG_CACHE_HOME` whatever the variable is
